name: Mark as updated

on:
  issue_comment:
    types:
      - created

jobs:
  mark-as-updated:
    if: "contains(github.event.issue.labels.*.name, 'awaiting update') && github.event.comment.user.login != 'codeforIATIbot'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "awaiting update"
          github_token: ${{ secrets.GH_TOKEN }}
          fail_on_error: true

  move-to-longstanding:
    if: "github.event.issue.state == 'open'"
    runs-on: ubuntu-latest
    needs: mark-as-updated
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: IATI data bugtracker
          column: Long-standing issues
          repo-token: ${{ secrets.GH_TOKEN }}
